<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>M.HASSANEIN</title>
    <meta content="portfolio of all my work in 3w academy" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/favicon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@1,700&display=swap" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
  * Template Name: MyResume - v2.1.0
  * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex flex-column justify-content-center">

        <nav class="nav-menu">
            <ul>
                <li class="active"><a href="#hero"><i class="bx bx-home"></i> <span>Accueil</span></a></li>
                <li><a href="#about"><i class="bx bx-user"></i> <span>Profil </span></a></li>
                <li><a href="#faire"><i class="bx bx-file-blank"></i> <span>Savoir faire</span></a></li>
                <li><a href="#etre"><i class="bx bx-file-blank"></i> <span>Savoir étre</span></a></li>
                <li><a href="#portfolio"><i class="bx bx-book-content"></i> <span>Mes réalisations</span></a></li>
                <li><a href="#services"><i class="bx bx-server"></i> <span>Services</span></a></li>
                <li><a href="#contact"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
                <li><a href="portflioen"><i class='bx bx-world'></i> <span>Anglais</span></a></li>
            </ul>
        </nav><!-- .nav-menu -->

    </header><!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex flex-column justify-content-center">
        <div class="container" data-aos="zoom-in" data-aos-delay="100">
            <h1>Mohammed HASSANEIN</h1>
            <p>Je suis <span class="typed" data-typed-items="Full Stack Développeur web"></span></p>
            <div class="social-links">
                <a href="https://twitter.com/momed9999?s=08" class="twitter" title="" target="_blank"><i
                        class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/momed999/" class="instagram" title="" target="_blank"><i
                        class="bx bxl-instagram"></i></a>
                <a href="https://github.com/M-HASSANEIN" class="google-plus" title="" target="_blank"><i
                        class="bx bxl-github"></i></a>
                <a href="https://www.linkedin.com/in/mohammed-hassanein-dev/" class="linkedin" title=""
                    target="_blank"><i class="bx bxl-linkedin"></i></a>
            </div>
            <!--cv button-------------------->
            <a href="assets/img/Mohammed.HASSANEIN-C.V.Fr.pdf" class=" btn cv-btn"
                download="Mohammed-HASSANEIN-FR">Télécharger
                Cv</a>
        </div>


    </section><!-- End Hero -->

    <main id="main">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-3">
                        <img src="assets/img/photocv.JPG" class="img-fluid" alt="profile">
                    </div>
                    <div class="col-lg-9 pt-4 pt-lg-0 content">
                        <h3>Full Stack Développeur web</h3>
                        <p class="font-italic">
                            Développeur web expérimenté en HTML, CSS, JavaScript, Node.js, PHP, MySQL, Symfony et Vue.
                            Je suis passionné par le Web et les nouvelles technologies que j'intègre dans mon travail.
                        </p>
                        <div class="row">
                            <div class="col-lg-9">
                                <ul>
                                    <!-- <li><i class="icofont-rounded-right"></i> <strong>Date de naissance:</strong> 1er
                                        Octobre 1986
                                    </li> -->
                                    <li><i class="icofont-rounded-right"></i> <strong>Tél:</strong> (+33)
                                        07-67-93-38-18
                                    </li>
                                    <li><i class="icofont-rounded-right"></i> <strong>Ville:</strong> Paris,
                                        FRANCE</li>
                                    <li><i class="icofont-rounded-right"></i> <a
                                            href="#contact"><strong>Email:</strong></a>
                                        mohammed.tareq.hassanien@hotmail.com</li>
                                    <li><i class="icofont-rounded-right"></i> <a
                                            href="https://mohammedhassaneinportfolio.herokuapp.com" title=""
                                            target="_blank"><strong>Site Web:</strong></a>
                                        mohammedhassaneinportfolio.herokuapp.com
                                    </li>
                                </ul>
                            </div>

                        </div>

                    </div>
                </div>

            </div>
        </section><!-- End About Section -->

        <!-- ======= Skills Section ======= -->
        <section id="skills" class="skills section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Compétences</h2>

                </div>

                <div class="row skills-content">

                    <div class="col-lg-6">

                        <div class="progress">
                            <span class="skill">HTML <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">CSS <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">SASS <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                        <div class="progress">
                            <span class="skill">JavaScript <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">JQUERY <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="88" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                        <div class="progress">
                            <span class="skill">Symfony <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">

                        <div class="progress">
                            <span class="skill">PHP <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">WordPress <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">Vue.js <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill"> Node.js <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                        <div class="progress">
                            <span class="skill"> Bootstrap <i class="val"></i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Skills Section -->
        <!--  know Section -->
        <section id="faire" class="resume">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>SAVOIR FAIRE</h2>
                    <p>Expérience solide dans la conception, le développement puis la maintenance d’applications et
                        projets Web dans des domaines variés après une analyse approfondie des besoins exprimés par les
                        clients.</p>
                </div>
            </div>
        </section>
        <section id="etre" class="resume">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>SAVOIR ÊTRE</h2>
                    <p>Très à l’aise dans le travail d’équipe et force de propositions, j’aime échanger et partager afin
                        de proposer des solutions en adéquation avec la demande initiale et dans les délais impartis. De
                        plus, mon parcours personnel me permet de m’adapter à tout type d’environnement.</p>
                </div>

            </div>
        </section>
        <!-- End know Section -->
        <!-- ======= Resume Section ======= -->
        <section id="resume" class="resume">
            <div class="container" data-aos="fade-up">

                <div class="row">

                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2 class="resume-title">EXPERIENCES PROFESSIONNELLES</h2>
                        </div>
                        <div class="resume-item">
                            <h4>Full Stack Web Developer JavaScript / PHP / Laravel</h4>
                            <h5>Oct 2021 - Dec 2021 ( 2 mois ) - Stage </h5>
                            <p><em>Raiseyour.biz– Paris, France </em></p>
                            <ul>
                                <li>Travailler avec les deux langues front-end et back-end.</li>
                                <li>Établir des plates-formes à part entière en utilisant une gamme de
                                    technologies
                                    différentes comme HTML, CSS, JavaScript, PHP, Node.js, et des frameworks
                                    comme
                                    Vue.js et Symfony.</li>
                                <li>Construire des bases de données en utilisant MySQL et MongoDB.</li>
                                <li>Tester et déboguer des sites Web et des applications.</li>
                            </ul>
                        </div>
                        <div class="resume-item">
                            <h4>Full Stack Développeur web</h4>
                            <h5>2020 - 2021 ( 4 mois ) - Stage</h5>
                            <p><em>3W Academy, Paris, FRANCE </em></p>
                            <ul>
                                <li>Analyser les besoins du client.</li>
                                <li>Établir des documents de spécifications techniques.</li>
                                <li>Créer et développer des sites Web avec CMS.</li>
                                <li>Intégrer des modèles et les adapter dynamiquement aux outils de l’utilisateur.</li>
                                <li>Développer des applications web avec des langages JavaScript et PHP.</li>
                                <li>Lier des applications à des bases de données en utilisant SQL.</li>
                                <li>Déterminer les phases et les procédures des tests techniques et fonctionnels des
                                    programmes et applications informatiques.</li>
                                <li>Analyser et résoudre les problèmes techniques.</li>
                            </ul>
                        </div>
                        <div class="resume-item">
                            <h4>Directeur Comptable </h4>
                            <h5>2019 - 2020</h5>
                            <p><em>SARL S.T.F. , Paris, FRANCE </em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Directeur Financier</h4>
                            <h5>2012 - 2017</h5>
                            <p><em>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS),Alexandrie, Egypte
                                </em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Directeur Comptable</h4>
                            <h5>2010 - 2012</h5>
                            <p><em>INTER LOG INTERNATIONAL LOGISTICS,Alexandrie, Egypte</em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Expert-Comptable</h4>
                            <h5>2007 - 2017</h5>
                            <p><em>Tareq Hassanein Cabinet d'expert-comptable, Alexandrie, Egypte</em></p>

                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2 class="resume-title">FORMATION</h2>
                        </div>
                        <div class="resume-item">
                            <h4>Développeur web </h4>

                            <p><em>3W Academy, Paris, FRANCE</em></p>
                            <p>Développeur Web , Gestion du Web / multimédia et webmaster-Level 5 & EUROPE</p>
                            <p>(Certification développeur-intégrateur dans le développement
                                d'applications Web)</p>
                        </div>
                        <div class="resume-item">
                            <h4>Bachelor commerce</h4>
                            <p><em>Faculté de Commerce, Université d’Alexandrie, Alexandrie, Egypte </em></p>
                            <p>Bachelor commerce (BAC + 4 )</p>
                        </div>
                    </div>
                </div>

            </div>
        </section><!-- End Resume Section -->

        <!-- ======= Portfolio Section ======= -->
        <section id="portfolio" class="portfolio section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Mes réalisations </h2>
                    <p>Passionné par la création et le développement de projets web, je me suis naturellement dirigé
                        vers une carrière de développeur web.</p>
                </div>

                <div class="row">
                    <div class="col-lg-12 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">

                    </div>
                </div>
                <?php include $template; ?>
                <!--  -->

            </div>

        </section><!-- End Portfolio Section -->
        <!-- ======= services Section ======= -->
        <section id="services" class="services">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Services</h2>
                    <p>Développe et met au point un projet d'application informatique, de la phase d'étude à son
                        intégration.</p>
                </div>
                <div class="servbox">
                    <div class=" " data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box iconbox-blue">
                            <!--box-1---------------->
                            <div class="s-box">
                                <!--img------------->
                                <div class="s-b-img">
                                    <!--type----------->
                                    <div class="s-type">Front-End</div>
                                    <!--name------->
                                    <img src="assets/img/s1.png">
                                </div>
                                <!--text----------------->
                                <div class="s-b-text">

                                    <a href="#">Programmer l’interface d’un site Internet ou d’une application en
                                        fonction du cahier des charges grâce à un langage de programmation (HTML, CSS,
                                        Javascript).</a>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class=" " data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-box iconbox-orange ">
                            <!--box-2---------------->
                            <div class="s-box">
                                <!--img------------->
                                <div class="s-b-img">
                                    <!--type----------->
                                    <div class="s-type">Back-End</div>
                                    <!--name------->
                                    <img src="assets/img/s2.png">
                                </div>
                                <!--text----------------->
                                <div class="s-b-text">
                                    <a href="#">Développer et faire évoluer les fonctionnalités techniques d’un site web
                                        ou d’une application grâce à un langage de programmation (Java,PHP,
                                        C,..).</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-title">

                        <p class="word">
                            <em> Je suis à l’écoute du marché et me montre disponible pour une
                                prise de contact afin
                                d’échanger
                                sur
                                vos éventuels projets ou besoins. </em>
                        </p>
                    </div>
                </div>

            </div>
        </section>
        <!-- End Services Section -->



        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Contact</h2>
                </div>

                <div class="row mt-1">

                    <div class=" col-xl-4 col-lg-6   ">
                        <div class="info">
                            <div class="address">
                                <i class="icofont-google-map"></i>
                                <h4>Lieu:</h4>
                                <p>Paris</p>
                                <p>FRANCE</p>
                            </div>

                            <div class="email">
                                <i class="icofont-envelope"></i>
                                <h4>E-mail :</h4>
                                <p>mohammed.tareq.hassanien@hotmail.com</p>
                            </div>

                            <div class="phone">
                                <i class="icofont-phone"></i>
                                <h4>Tél:</h4>
                                <p>(+33) 07-67-93-38-18</p>
                            </div>

                        </div>

                    </div>

                    <div id="email" class=" col-xl-8 col-lg-6   mt-5 mt-lg-0">

                        <form action="contact" method="post" class="php-email-form">
                            <div class="form-row">
                                <div class="col-md-6 form-group">
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="Votre nom" data-rule="minlen:4"
                                        data-msg="Please enter at least 4 chars" />
                                    <div class="validate"></div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <input type="email " class="form-control" name="email" id="email"
                                        placeholder="Votre e-mail " data-rule="email"
                                        data-msg="Please enter a valid email" />
                                    <div class="validate"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" id="subject" placeholder="Sujet"
                                    data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                                <div class="validate"></div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" rows="5" data-rule="required"
                                    data-msg="Please write something for us" placeholder="Message"
                                    id="message"></textarea>
                                <div class="validate"></div>
                            </div>
                            <div class="mb-3">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Votre message a été envoyé. Merci! </div>
                            </div>
                            <div class="text-center"><button type="submit" name="submit">Envoyer le
                                    message</button>
                            </div>
                        </form>

                    </div>

                </div>

            </div>
        </section><!-- End Contact Section -->

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <h3>Mohammed HASSANEIN</h3>
            <p>Full Stack Développeur web</p>
            <div class="social-links">
                <a href="https://twitter.com/momed9999?s=08" class="twitter" title="" target="_blank"><i
                        class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/momed999/" class="instagram" title="" target="_blank"><i
                        class="bx bxl-instagram"></i></a>
                <a href="https://github.com/M-HASSANEIN" class="google-plus" title="" target="_blank"><i
                        class="bx bxl-github"></i></a>
                <a href="https://www.linkedin.com/in/mohammed-hassanein-dev/" class="linkedin" title=""
                    target="_blank"><i class="bx bxl-linkedin"></i></a>
            </div>
            <!--  <div class="copyright">
                &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
            </div> -->
            <!--  <div class="credits"> -->
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: [license-url] -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
            <!--    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div> -->
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/jquery/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="assets/vendor/counterup/counterup.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/venobox/venobox.min.js"></script>
    <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="assets/vendor/typed.js/typed.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>

</body>

</html>