<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>M.HASSANEIN</title>
    <meta content="portfolio of all my work in 3w academy" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@1,700&display=swap" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">
    <!-- =======================================================
  * Template Name: MyResume - v2.1.0
  * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Mobile nav toggle button ======= -->
    <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont-navigation-menu"></i></button>

    <!-- ======= Header ======= -->
    <header id="header" class="d-flex flex-column justify-content-center">

        <nav class="nav-menu">
            <ul>
                <li class="active"><a href="#hero"><i class="bx bx-home"></i> <span>Home</span></a></li>
                <li><a href="#about"><i class="bx bx-user"></i> <span>About</span></a></li>
                <li><a href="#resume"><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
                <li><a href="#portfolio"><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
                <li><a href="#services"><i class="bx bx-server"></i> <span>Services</span></a></li>
                <li><a href="#contact"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
                <li><a href="portfliofr">Fr <span>French</span></a></li>
            </ul>
        </nav><!-- .nav-menu -->

    </header><!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex flex-column justify-content-center">
        <div class="container" data-aos="zoom-in" data-aos-delay="100">
            <h1>Mohammed HASSANEIN</h1>
            <p>I'm <span class="typed" data-typed-items="Full Stack Web Developer"></span></p>
            <div class="social-links">
                <a href="https://twitter.com/momed9999?s=08" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/momed999/" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="https://github.com/Tiko8690" class="google-plus"><i class="bx bxl-github"></i></a>
                <a href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a" class="linkedin"><i
                        class="bx bxl-linkedin"></i></a>
            </div>
            <!--cv button-------------------->
            <!--cv button-------------------->

            <a href="assets/img/Mohammed HASSANEIN C.V.EN.pdf" class=" btn cv-btn"
                download="Mohammed-HASSANEIN">Download
                Cv</a>

        </div>
    </section><!-- End Hero -->

    <main id="main">

        <!-- ======= About Section ======= -->
        <section id="about" class="about">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-3">
                        <img src="assets/img/photocv.JPG" class="img-fluid" alt="profile">
                    </div>
                    <div class="col-lg-9 pt-4 pt-lg-0 content">
                        <h3>Full Stack Web Developer.</h3>
                        <p class="font-italic">
                            Certified full-stack web developer with experience in HTLM, CSS, JavaScript, PHP, VUE.JS,
                            J.Query and My SQL.
                        </p>
                        <div class="row">
                            <div class="col-lg-9">
                                <ul>
                                    <li><i class="icofont-rounded-right"></i> <strong>Birthday:</strong> 1 October 1986
                                    </li>
                                    <li><i class="icofont-rounded-right"></i> <strong>Phone:</strong> (+33) 076-793-3818
                                    </li>
                                    <li><i class="icofont-rounded-right"></i> <strong>City:</strong> Paris,
                                        FRANCE</li>
                                    <li><i class="icofont-rounded-right"></i> <strong>Email:</strong>
                                        mohammed.tareq.hassanien@hotmail.com</li>
                                    <li><i class="icofont-rounded-right"></i> <strong>Website:</strong>
                                        mohammedhassaneinportfolio.herokuapp.com
                                    </li>
                                </ul>
                            </div>

                        </div>

                    </div>
                </div>

            </div>
        </section><!-- End About Section -->

        <!-- ======= Skills Section ======= -->
        <section id="skills" class="skills section-bg">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Skills</h2>

                </div>

                <div class="row skills-content">

                    <div class="col-lg-6">

                        <div class="progress">
                            <span class="skill">HTML <i class="val">90%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">CSS <i class="val">90%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">JavaScript <i class="val">85%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">JQUERY <i class="val">88%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="88" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                        <div class="progress">
                            <span class="skill">Symfony 5.2 <i class="val">75%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">

                        <div class="progress">
                            <span class="skill">PHP <i class="val">90%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">WordPress <i class="val">85%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill">VUE JS <i class="val">85%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>

                        <div class="progress">
                            <span class="skill"> SASS <i class="val">90%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                        <div class="progress">
                            <span class="skill"> Bootstraap <i class="val">85%</i></span>
                            <div class="progress-bar-wrap">
                                <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0"
                                    aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </section><!-- End Skills Section -->
        <!-- End know Section -->
        <section id="resume" class="resume">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>ABLE TO DO </h2>
                    <p>Solid experience in the design, development and maintenance of applications and
                        Web projects in various fields after an in-depth analysis of the needs expressed by the
                        clients.</p>
                </div>
                <div class="section-title">
                    <h2>KNOW-HOW</h2>
                    <p>Very comfortable with teamwork and a force for proposals, I like to discuss and share in order
                        to offer solutions in line with the initial request and on time. Of
                        moreover, my personal background allows me to adapt to any type of environment.</p>
                </div>

            </div>
        </section>
        <!-- End know Section -->
        <!-- ======= Resume Section ======= -->
        <section id="resume" class="resume">
            <div class="container" data-aos="fade-up">
                <div class="row">

                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2 class="resume-title">Employment History </h2>
                        </div>
                        <div class="resume-item">
                            <h4>Full Stack Web Developer</h4>
                            <h5>2020 - 2021</h5>
                            <p><em>3W Academy, Paris, FRANCE </em></p>
                            <ul>
                                <li>Website creation and develop it into a commercial website with the CMS.</li>
                                <li>Integration of models and dynamically adapt them to the user's tools.</li>
                                <li>Develop web applications with JavaScript and PHP languages.</li>
                                <li>Linking Applications to Databases Using SQL.</li>
                                <li>Determine the phases and procedures of technical and functional tests of computer
                                    programs and applications .</li>
                                <li>Analyser des problemes techniques.</li>
                                <li>Manage projects or tasks at a given time while under pressure .</li>
                                <li>Analyze customer needs . </li>
                            </ul>
                        </div>
                        <div class="resume-item">
                            <h4>Chief Financial Officer (CFO) </h4>
                            <h5>2019 - 2020</h5>
                            <p><em>SARL S.T.F. , Paris, FRANCE </em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Chief Financial officer (CFO)</h4>
                            <h5>2012 - 2017</h5>
                            <p><em>LOGISTICS INTERNATIONAL OUTSOURCING NETWORKING SERVICES (LIONS) , Alexandria, Egypt
                                </em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Branche Accountant Manager</h4>
                            <h5>2010 - 2012</h5>
                            <p><em>INTER LOG INTERNATIONAL LOGISTICS ,Alexandria , Egypt</em></p>

                        </div>
                        <div class="resume-item">
                            <h4>Chartered Accountant</h4>
                            <h5>2007 - 2017</h5>
                            <p><em>Tareq Hassanein Chartered Accountant Office , Alexandria , Egypt</em></p>

                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2 class="resume-title">Education</h2>
                        </div>
                        <div class="resume-item">
                            <h4>Bachelor of development of Web applications</h4>
                            <p><em>3W Academy, Paris, FRANCE</em></p>
                            <p>Web Developer, Web / Multimedia Management and Webmaster-Level 5 & EUROPE. </p>
                            <p>(Developer-integrator certification in web application development). </p>
                        </div>
                        <div class="resume-item">
                            <h4>Bachelor of commerce &amp; accounting</h4>
                            <p><em>Faculty of Commerce , University of Alexandria, Alexandria Egypt </em></p>
                            <p>Bachelor of commerce</p>
                        </div>
                    </div>
                </div>

            </div>
        </section><!-- End Resume Section -->

        <!-- ======= Portfolio Section ======= -->
        <section id="portfolio" class="portfolio section-bg">
            <div class="container" data-aos="fade-up">
                <div class="section-title">
                    <h2>Portfolio</h2>
                    <p>Passionate about the creation and development of web projects, I naturally headed for a career as
                        a web developer.</p>
                </div>
                <div class="row">
                    <div class="col-lg-12 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
                    </div>
                </div>
                <?php include $template;?>
            </div>
        </section><!-- End Portfolio Section -->
        <!-- ======= services Section ======= -->
        <section id="services" class="services">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Services</h2>
                    <p>Develops and perfects a computer application project, from the study phase to its integration.
                    </p>
                </div>
                <div class="servbox">
                    <div class=" " data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box iconbox-blue">
                            <!--box-1---------------->
                            <div class="s-box">
                                <!--img------------->
                                <div class="s-b-img">
                                    <!--type----------->
                                    <div class="s-type">Front-End</div>
                                    <!--name------->
                                    <img src="assets/img/s1.png">
                                </div>
                                <!--text----------------->
                                <div class="s-b-text">
                                    <a href="#">Responsible for implementing visual and
                                        interactive elements that users engage with through their web browser when using
                                        a web application.</a>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class=" " data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-box iconbox-orange ">
                            <!--box-2---------------->
                            <div class="s-box">
                                <!--img------------->
                                <div class="s-b-img">
                                    <!--type----------->
                                    <div class="s-type">Back-End</div>
                                    <!--name------->
                                    <img src="assets/img/s2.png">
                                </div>
                                <!--text----------------->
                                <div class="s-b-text">
                                    <a href="#">Responsible for server-side web application
                                        logic. Back-end developers
                                        are usually write the web services and APIs used by front-end developers and
                                        mobile application developers.</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-title">

                        <p class="word">
                            <em> I listen to the market and show myself available for
                                making contact in order
                                to change
                                sure
                                your possible projects or needs. </em>
                        </p>
                    </div>
                </div>

            </div>
        </section>
        <!-- End Services Section -->



        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2>Contact</h2>
                </div>

                <div class="row mt-1">

                    <div class=" col-xl-4 col-lg-6   ">
                        <div class="info">
                            <div class="address">
                                <i class="icofont-google-map"></i>
                                <h4>Location:</h4>
                                <p>Paris</p>
                                <p>FRANCE</p>
                            </div>

                            <div class="email">
                                <i class="icofont-envelope"></i>
                                <h4>Email:</h4>
                                <p>mohammed.tareq.hassanien@hotmail.com</p>
                            </div>

                            <div class="phone">
                                <i class="icofont-phone"></i>
                                <h4>Call:</h4>
                                <p>(+33) 076-793-3818</p>
                            </div>

                        </div>

                    </div>

                    <div class=" col-xl-8 col-lg-6   mt-5 mt-lg-0">

                        <form action="contact" method="post" role="form" class="php-email-form">
                            <div class="form-row">
                                <div class="col-md-6 form-group">
                                    <input type="text" name="name" class="form-control" id="name"
                                        placeholder="Your Name" data-rule="minlen:4"
                                        data-msg="Please enter at least 4 chars" />
                                    <div class="validate"></div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <input type="email" class="form-control" name="email" id="email"
                                        placeholder="Your Email" data-rule="email"
                                        data-msg="Please enter a valid email" />
                                    <div class="validate"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" id="subject"
                                    placeholder="Subject" data-rule="minlen:4"
                                    data-msg="Please enter at least 8 chars of subject" />
                                <div class="validate"></div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" rows="5" data-rule="required"
                                    data-msg="Please write something for us" placeholder="Message"></textarea>
                                <div class="validate"></div>
                            </div>
                            <div class="mb-3">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Your message has been sent. Thank you!</div>
                            </div>
                            <div class="text-center"><button type="submit" name="submit">Send Message</button></div>
                        </form>

                    </div>

                </div>

            </div>
        </section><!-- End Contact Section -->

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <h3>Mohammed HASSANEIN</h3>
            <p>Full Stack Web Developer</p>
            <div class="social-links">
                <a href="https://twitter.com/momed9999?s=08" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://www.instagram.com/momed999/" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="https://github.com/Tiko8690" class="google-plus"><i class="bx bxl-github"></i></a>
                <a href="https://www.linkedin.com/in/mohammed-hassanein-4a9b172a" class="linkedin"><i
                        class="bx bxl-linkedin"></i></a>
            </div>
            <!--  <div class="copyright">
                &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
            </div> -->
            <!--  <div class="credits"> -->
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: [license-url] -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
            <!--    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div> -->
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="assets/vendor/jquery/jquery.min.js"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="assets/vendor/php-email-form/validate.js"></script>
    <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="assets/vendor/counterup/counterup.min.js"></script>
    <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="assets/vendor/venobox/venobox.min.js"></script>
    <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="assets/vendor/typed.js/typed.min.js"></script>
    <script src="assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>

</body>

</html>